trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'copystorageaccount'
    ScriptType: 'FilePath'
    ScriptPath: 'arm/script.ps1'
    ScriptArguments: -Location 'centralindia' -ResourceGroupName 'ResourceDeployment' -TemplateFile arm/script.ps1
    azurePowerShellVersion: 'LatestVersion'
